### ISSUE TITLE
Mapping images

### ISSUE THREAD

**Issue by rajesh4472** [HackBio-Genomics-One-B/Genomics-One-B#5]
![IMG_20210820_131657](https://user-images.githubusercontent.com/88301709/130201692-cd9068d3-9030-4540-aae5-7ff193f70e6b.jpg)
![IMG_20210820_131439](https://user-images.githubusercontent.com/88301709/130202177-3aacb599-8593-45a0-95af-699048557998.jpg)
![IMG_20210820_130913](https://user-images.githubusercontent.com/88301709/130202234-9f04125d-0dde-488f-9459-1dda8ad458de.jpg)

**Comment by rajesh4472** [comment]
Mapping images

**Comment by nahid18** [comment]
added
